import pandas as pd
import base64
from datetime import datetime

class StallionReporter:
    """
    The Storyteller.
    Generates textual insights and exports professional HTML reports.
    """
    
    def __init__(self, ai_engine):
        self.ai = ai_engine # Reference to the DashboardBrain/CoPilot to use the LLM

    def generate_narrative(self, db_engine, config):
        """
        Reads the current dashboard config and data, then asks AI for an Executive Summary.
        """
        # 1. Prepare Context
        kpi_text = ""
        if "kpi_cards" in config:
            for kpi in config["kpi_cards"]:
                kpi_text += f"- {kpi.get('label', 'Metric')}: {kpi.get('column')} ({kpi.get('operation')})\n"
        
        chart_text = ""
        if "charts" in config:
            for chart in config["charts"]:
                chart_text += f"- {chart.get('title')}: showing {chart.get('y_column')} by {chart.get('x_column')}\n"

        system_prompt = """
        You are a Chief Data Officer. Write a concise, 3-bullet point Executive Summary based on the provided dashboard structure and data preview.
        Focus on trends, anomalies, and actionable insights.
        Output Format: Markdown.
        """
        
        # We assume the AI engine has a generic call method or we use the one from Copilot
        # For simplicity in this architecture, we reuse the prompt logic here or assume 'ai_engine' has a generic 'ask' method.
        # Since we didn't strictly define a generic 'ask' in Step 3, we will construct the request here.
        
        # Get Data Summary using DuckDB
        try:
            summary_df = db_engine.conn.execute("SUMMARIZE source_data").df()
            data_summary = summary_df.to_string()
        except Exception:
            data_summary = "Data summary unavailable."

        user_msg = f"""
        Dashboard Structure:
        {kpi_text}
        {chart_text}
        
        Data Summary:
        {data_summary}
        
        Write the Executive Summary now.
        """
        
        # We need to access the internal generation logic. 
        # To avoid circular imports or complexity, we will assume this is called from the App where we have the 'brain' or 'copilot'.
        # For now, we return the prompt components so the App can call the AI.
        return system_prompt, user_msg

    @staticmethod
    def create_html_report(narrative, kpi_values, config, filename="stallion_report.html"):
        """
        Generates a standalone HTML file with the insights and KPIs.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        # Generate KPI HTML Grid
        kpi_html = ""
        for k, v in kpi_values.items():
            kpi_html += f"""
            <div class="kpi-card">
                <h3>{k}</h3>
                <h1>{v}</h1>
            </div>
            """

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Stallion Analytics Report</title>
            <style>
                body {{ font-family: 'Helvetica', sans-serif; background-color: #f4f4f9; color: #333; padding: 40px; }}
                .header {{ border-bottom: 2px solid #00E5FF; padding-bottom: 20px; margin-bottom: 30px; }}
                h1 {{ color: #141928; }}
                .timestamp {{ color: #666; font-size: 0.9em; }}
                
                .kpi-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 40px; }}
                .kpi-card {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); border-left: 5px solid #0072FF; }}
                .kpi-card h3 {{ margin: 0 0 10px 0; color: #888; font-size: 14px; text-transform: uppercase; }}
                .kpi-card h1 {{ margin: 0; font-size: 32px; color: #141928; }}
                
                .narrative {{ background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); }}
                .narrative h2 {{ margin-top: 0; color: #0072FF; }}
                .footer {{ margin-top: 50px; text-align: center; color: #aaa; font-size: 12px; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>{config.get('dashboard_title', 'Analytics Report')}</h1>
                <div class="timestamp">Generated by Stallion AI on {timestamp}</div>
            </div>
            
            <div class="kpi-grid">
                {kpi_html}
            </div>
            
            <div class="narrative">
                <h2>Executive Summary</h2>
                {narrative.replace(chr(10), '<br>')}
            </div>
            
            <div class="footer">
                Generated by Stallion Analytics Engine
            </div>
        </body>
        </html>
        """
        
        # Create Download Link
        b64 = base64.b64encode(html_content.encode()).decode()
        href = f'<a href="data:file/html;base64,{b64}" download="{filename}" class="report-btn">📥 Download Full Report (HTML)</a>'
        return href